feat(weekTableTaskDayCell): Disable work hour inputs on time page tha…
progwise/timebook pull request #634
Opened 2023-03-06 11:30 UTC by TonySchroeder

Versuch die Inputs zu deaktivieren, hoffe das geht so? Aber immer noch Probleme mit dem Sonntag.

2023-03-06 17:20 UTC, PascalHelbig commented on apps/web/frontend/components/hourInput.tsx
> +  isdisabled?: boolean
Please use camelCase, so either `disabled` or `isDisabeld`.
I would prefer `disabled`, as the attribute on an HTML input is also named `disabled`.

2023-03-06 17:21 UTC, PascalHelbig commented on apps/web/frontend/components/hourInput.tsx
> +      type={props.isdisabled ? 'hidden' : ''}
Let's make it gray and not hidden. :)

2023-03-06 17:23 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +      {projectsLoading && <Spinner />}
I think it is forbidden to put any element other than `TableCell` in a `TableRow`.

2023-03-06 17:42 UTC, PascalHelbig requested changes
See my comments. 😅

2023-03-06 17:42 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +          // console.log('isDayBefore: ', isDayBefore)
We don't like unused code.

```suggestion
```

2023-03-06 17:42 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +  })
All the information we need (start and end date) exists in the parent component (`WeekTableProjectRowGroup`). Why not just pass it off as props?

2023-03-06 17:42 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +  const endDate = new Date(currentProjekt?.endDate ?? '')
This will break: `new Date('')` creates an `Invalid Date`

2023-03-06 17:42 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +          const isDayAfter = isAfter(day, endDate)
I think you need a logic like this:
```ts
const isDisabled = (projectStart && isBefore(day, projectStart)) ||  (projectEnd && isAfter(day, projectEnd)
```
(not tested)

2023-03-07 04:55 UTC, TonySchroeder commented
Changes made, but the problem when a start/end date falls on a Sunday should be looked at again.

2023-03-13 08:20 UTC, PascalHelbig requested changes
I found two smaller code style issues and the bug you mentioned in your last comment.

Please have a look. ☺️

2023-03-13 08:20 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +  projectEnd?: string | null
To me, that looks messy. You pass individual fields from the project (start and end), but also a whole task object.
Moreover, the `task` object also contains the `project` field. What's wrong with using the `task` object to read start and end fields?


<img width="902" alt="image" src="https://user-images.githubusercontent.com/1886867/224640261-813467bb-65f4-4015-89d3-d1a710b0a778.png">

2023-03-13 08:20 UTC, PascalHelbig commented on apps/web/frontend/components/weekTable/weekTableTaskRow.tsx
> +              (projectEnd ? isAfter(day, new Date(projectEnd)) : false)
You should use `parseISO(...)` from `date-fns`. 

`new Date()` will set the time to 0' a clock Greenwich Mean Time, which is 1' a clock for us.
`parseISO` will set the time to 0' a clock of the timezone of the user, so 0' a clock for us.

If `projectStart` and `day` are set to `2023-01-01`, your code compares:
```
 is '2023-01-01 00:00:00' before '2023-01-01 01:00:00'?
```
This condition is `true` so the input is wrongly disabled.

2023-03-17 08:02 UTC, PascalHelbig commented
@TonySchroeder, please link the ticket in the PR description before merging this PR.

2023-03-17 15:43 UTC, merged