Feat/#739 loading spinner all pages
progwise/timebook pull request #759
Opened 2023-04-21 03:16 UTC by TonySchroeder

2023-04-21 03:17 UTC, TonySchroeder commented
Closed [#739](https://github.com/progwise/timebook/issues/739)

2023-05-12 13:27 UTC, moncapitaine commented on apps/web/frontend/components/hourInput/hourInput.tsx
> +  mutationLoading?: boolean
hourInput does not need spinner, because it already implements isDirty.

2023-05-12 13:28 UTC, moncapitaine commented on apps/web/frontend/components/reportForm/reportForm.tsx
> +  const [{ fetching: loadProjects, data: projectsData }] = useQuery({
fetchingProjects better. loadProjects sounds like a method.

2023-05-12 13:28 UTC, moncapitaine commented on apps/web/frontend/components/reportForm/reportForm.tsx
> +  const [{ fetching: loadReportGrouped, data: reportGroupedData }] = useQuery({
same

2023-05-12 13:32 UTC, moncapitaine commented on apps/web/frontend/components/weekTable/weekTableTaskDayCell.tsx
> +        mutationLoading={mutationLoading}
remove prop, see above.

2023-05-12 13:32 UTC, moncapitaine requested changes
please remove spinner from hourInput and look at the comments.

2023-06-02 14:15 UTC, moncapitaine commented on apps/web/frontend/components/reportForm/reportForm.tsx
> +            {fetchingProjects && fetchingReports ? (
Isn't this an 'or'?
```suggestion
            {fetchingProjects || fetchingReports ? (
```

2023-06-02 14:16 UTC, moncapitaine requested changes
a single && instead of a || was found. Hope I am right about it. Please check

2023-11-24 14:08 UTC, PascalHelbig commented
we will use daisy ui instead

2023-11-24 14:08 UTC, closed without merging