draft: switches to button for task locking
progwise/timebook pull request #842
Opened 2024-02-01 09:55 UTC by inpaceee

closes: #822

2024-02-02 12:57 UTC, moncapitaine requested changes
Change the icon of the lock, e.g. 
<img width="73" alt="image" src="https://github.com/progwise/timebook/assets/16672443/65952ba6-3743-4f94-a461-ee1d653ea1e3">

(but need to change the complete icon set then because boxIcons have none).

2024-02-02 13:22 UTC, moncapitaine requested changes
the lock/unlock is the wrong one, you need to lock/unlock the task for every user which is available through the taskUpdate mutation and not the lock/unlock mutations

2024-02-09 15:49 UTC, PascalHelbig commented on apps/web/frontend/components/lockTaskButton.tsx
> +  const [{ fetching }, updateTaskLock] = useMutation(TaskUpdateMutationDocument)
```suggestion
  const [{ fetching }, updateTask] = useMutation(TaskUpdateMutationDocument)
```

2024-02-09 16:00 UTC, PascalHelbig approved these changes

2024-02-09 16:00 UTC, moncapitaine approved these changes

2024-02-09 16:17 UTC, merged