Removes the regenerate invite link for the non admin user.
progwise/timebook pull request #846
Opened 2024-02-01 17:31 UTC by splendidcomputer

2024-02-02 13:39 UTC, PascalHelbig requested changes

2024-02-02 13:39 UTC, PascalHelbig commented on apps/web/frontend/components/inviteLink.tsx
> +        {Role.Admin && (
Who does this work?

2024-02-02 14:22 UTC, splendidcomputer commented on apps/web/frontend/components/inviteLink.tsx
> +        {Role.Admin && (
It does not work.

2024-02-09 13:04 UTC, PascalHelbig commented
Will be fixed in #853

2024-02-09 13:04 UTC, closed without merging