feat: adds tabs for tasks and members of a project
progwise/timebook pull request #858
Opened 2024-02-07 12:17 UTC by inpaceee

closes: #823

2024-02-07 14:46 UTC, moncapitaine requested changes
- double headlines need to be removed for tasks and members, tab header is enough
- add e2e playwright test for it.

2024-02-07 14:47 UTC, moncapitaine commented
https://playwright.dev/docs/intro

2024-02-07 14:48 UTC, moncapitaine commented
```
pnpm run playwright --ui
```

2024-02-09 16:51 UTC, PascalHelbig approved these changes

2024-02-12 13:31 UTC, moncapitaine approved these changes

2024-02-12 14:45 UTC, merged