Paying monthly
progwise/timebook pull request #937
Opened 2024-10-11 09:35 UTC by inpaceee

closes: #934

2024-11-20 07:56 UTC, PascalHelbig requested changes
See the comments and also make sure, the new env vars are present in pulumi.

2024-11-20 07:56 UTC, PascalHelbig commented on apps/web/frontend/components/organizationForm/organizationForm.tsx
> +/* eslint-disable unicorn/no-nested-ternary */
Is this needed?

2024-11-20 07:56 UTC, PascalHelbig commented on apps/web/frontend/components/organizationForm/organizationSubscriptionStatusLabel.tsx
> +`)
Is this fragment used?

2024-11-20 07:56 UTC, PascalHelbig commented on apps/web/package.json
> +    "@paypal/checkout-server-sdk": "^1.0.3",
Is this dependency still used?

2024-11-20 07:56 UTC, PascalHelbig commented on apps/web/pages/organizations/[id]/checkout.page.tsx
> +
```suggestion
```

2024-11-20 07:56 UTC, PascalHelbig commented on apps/web/pages/organizations/[id]/checkout.page.tsx
> +const PayPalPage = (): JSX.Element => {
Let's use a name that matches the route

```suggestion
const CheckoutPage = (): JSX.Element => {
```

2024-11-22 09:53 UTC, PascalHelbig commented on .github/workflows/node.js.yml
> +          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
We need `NEXT_PUBLIC_PAYPAL_CLIENT_ID` and `PAYPAL_URL` as well. Otherwise, both envs would be undefined on prod.

2024-11-22 09:53 UTC, PascalHelbig commented on apps/web/pages/organizations/[id]/subscriptionStatusOrganizationLink/subscriptionStatusOrganizationLink.tsx
> +          <FaCircleCheck className="text-xl" />
`SubscriptionStatusOrganizationLink` should not decide which icon and which CSS rules the alert should have.

Take a look at #951. This separates the implementation details of the alert from the usage.

2024-11-22 09:53 UTC, PascalHelbig commented on packages/backend/src/graphql/organization/organization.ts
> +    paypalSubscriptionId: t.withAuth({ isLoggedIn: true }).exposeString('paypalSubscriptionId', { nullable: true }),
```suggestion
    paypalSubscriptionId: t.exposeString('paypalSubscriptionId', { nullable: true }),
```

2024-11-25 12:21 UTC, YohannesTesfay approved these changes

2024-11-25 14:04 UTC, moncapitaine approved these changes

2024-11-25 14:06 UTC, PascalHelbig approved these changes

2024-11-25 14:06 UTC, merged